name: 1.0$(rev:.r)
trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: "dotnet install sdk"
    inputs:
      packageType: 'sdk'
  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
      command: "restore"
      projects: "src/Pdfless/Pdfless.csproj"
  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      command: "build"
      projects: "./src/Pdfless/Pdfless.csproj"
      arguments: "-c Release"
  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: pack
      packagesToPack: src/Pdfless/Pdfless.csproj
      versioningScheme: byBuildNumber
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: Nuget
